/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutosDAO;
import Model.Produtos;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Moura
 */
public class TelaCaixa extends javax.swing.JFrame {

    /**
     * Creates new form TelaCaixa
     */
    public void listar(){
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listar();
        DefaultTableModel dados =(DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPreco(),
            });
        }
    }
    
    public TelaCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_geral = new javax.swing.JTabbedPane();
        painel_caixa = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtQuant2 = new javax.swing.JTextArea();
        txtTotal = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPreco2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtNome2 = new javax.swing.JTextArea();
        txtQuant1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCpf1 = new javax.swing.JFormattedTextField();
        txtContato = new javax.swing.JFormattedTextField();
        painel_consulta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        painel_caixa.setLayout(null);

        txtQuant2.setColumns(20);
        txtQuant2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtQuant2.setLineWrap(true);
        txtQuant2.setRows(5);
        jScrollPane4.setViewportView(txtQuant2);

        painel_caixa.add(jScrollPane4);
        jScrollPane4.setBounds(220, 230, 170, 250);
        painel_caixa.add(txtTotal);
        txtTotal.setBounds(600, 270, 170, 90);

        btnAdicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionar.setText("ADICIONAR");
        painel_caixa.add(btnAdicionar);
        btnAdicionar.setBounds(570, 160, 150, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("TOTAL:");
        painel_caixa.add(jLabel3);
        jLabel3.setBounds(650, 250, 70, 14);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("PREÇO");
        painel_caixa.add(jLabel1);
        jLabel1.setBounds(450, 200, 70, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("NOME");
        painel_caixa.add(jLabel4);
        jLabel4.setBounds(90, 210, 70, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("QUANTIDADE");
        painel_caixa.add(jLabel5);
        jLabel5.setBounds(240, 210, 140, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("PREÇO:");
        painel_caixa.add(jLabel6);
        jLabel6.setBounds(450, 120, 50, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("NOME:");
        painel_caixa.add(jLabel7);
        jLabel7.setBounds(80, 40, 40, 15);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("CPF:");
        painel_caixa.add(jLabel8);
        jLabel8.setBounds(90, 80, 30, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("CONTATO:");
        painel_caixa.add(jLabel9);
        jLabel9.setBounds(60, 120, 60, 15);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("CÓDIGO DO PRODUTO:");
        painel_caixa.add(jLabel10);
        jLabel10.setBounds(370, 40, 140, 15);
        painel_caixa.add(txtPreco);
        txtPreco.setBounds(510, 120, 210, 20);
        painel_caixa.add(txtNome);
        txtNome.setBounds(130, 40, 210, 20);
        painel_caixa.add(txtCod);
        txtCod.setBounds(510, 40, 210, 20);

        btnFinalizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFinalizar.setText("FINALIZAR PAGAMENTO");
        painel_caixa.add(btnFinalizar);
        btnFinalizar.setBounds(600, 390, 170, 70);

        txtPreco2.setColumns(20);
        txtPreco2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPreco2.setLineWrap(true);
        txtPreco2.setRows(5);
        jScrollPane5.setViewportView(txtPreco2);

        painel_caixa.add(jScrollPane5);
        jScrollPane5.setBounds(400, 230, 170, 250);

        txtNome2.setColumns(20);
        txtNome2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNome2.setLineWrap(true);
        txtNome2.setRows(5);
        jScrollPane6.setViewportView(txtNome2);

        painel_caixa.add(jScrollPane6);
        jScrollPane6.setBounds(40, 230, 170, 250);
        painel_caixa.add(txtQuant1);
        txtQuant1.setBounds(510, 80, 210, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("QUANTIDADE:");
        painel_caixa.add(jLabel11);
        jLabel11.setBounds(420, 80, 80, 15);

        try {
            txtCpf1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painel_caixa.add(txtCpf1);
        txtCpf1.setBounds(130, 80, 210, 20);

        try {
            txtContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painel_caixa.add(txtContato);
        txtContato.setBounds(130, 120, 210, 20);

        painel_geral.addTab("CAIXA", painel_caixa);

        painel_consulta.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NOME:");
        painel_consulta.add(jLabel2);
        jLabel2.setBounds(20, 40, 40, 15);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        painel_consulta.add(txtPesquisar);
        txtPesquisar.setBounds(60, 40, 200, 20);

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        painel_consulta.add(btnPesquisar);
        btnPesquisar.setBounds(280, 40, 120, 23);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "PREÇO"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        painel_consulta.add(jScrollPane2);
        jScrollPane2.setBounds(0, 90, 810, 390);

        painel_geral.addTab("CONSULTAR PRODUTOS", painel_consulta);

        getContentPane().add(painel_geral);
        painel_geral.setBounds(0, 0, 820, 510);

        setSize(new java.awt.Dimension(832, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String nome = "%"+txtPesquisar.getText()+"%";
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.filtrar(nome);
        DefaultTableModel dados =(DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPreco(),
                
            });
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        String nome = "%"+txtPesquisar.getText()+"%";
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.filtrar(nome);
        DefaultTableModel dados =(DefaultTableModel) tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPreco(),
                
            });
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        painel_geral.setSelectedIndex(0);
        txtCod.setText(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
        txtNome.setText(tabela.getValueAt(tabela.getSelectedRow(),1).toString());
        txtPreco.setText(tabela.getValueAt(tabela.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tabelaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel painel_caixa;
    private javax.swing.JPanel painel_consulta;
    private javax.swing.JTabbedPane painel_geral;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCod;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JFormattedTextField txtCpf1;
    public static javax.swing.JTextField txtNome;
    public static javax.swing.JTextArea txtNome2;
    public static javax.swing.JTextField txtPesquisar;
    public static javax.swing.JTextField txtPreco;
    public static javax.swing.JTextArea txtPreco2;
    private javax.swing.JTextField txtQuant1;
    public static javax.swing.JTextArea txtQuant2;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
